import { Hono } from "hono";
import { getDb } from "../db/index.js";
import { ObjectId } from "mongodb";

const router = new Hono();

// ─── انواع پرداخت پیش‌فرض ────────────────────────────────────────────────────
export const DEFAULT_PAYMENT_TYPES = [
  { code: "CASH",   title: "نقدی",           method: "نقدی",          defaultAccount: "صندوق",            isDefault: true },
  { code: "POS",    title: "کارتخوان (POS)", method: "کارتخوان",      defaultAccount: "بانک",             isDefault: true },
  { code: "C2C",    title: "کارت به کارت",   method: "کارت به کارت",  defaultAccount: "بانک",             isDefault: true },
  { code: "HAVALE", title: "حواله بانکی",    method: "حواله بانکی",   defaultAccount: "بانک",             isDefault: true },
  { code: "PAYA",   title: "پایا",           method: "پایا",          defaultAccount: "بانک",             isDefault: true },
  { code: "SATNA",  title: "ساتنا",          method: "ساتنا",         defaultAccount: "بانک",             isDefault: true },
  { code: "ONLINE", title: "اینترنتی",       method: "اینترنتی",      defaultAccount: "بانک",             isDefault: true },
  { code: "CHECK",  title: "چک",             method: "چک",            defaultAccount: "اسناد پرداختنی",  isDefault: true },
  { code: "DRAFT",  title: "سفته",           method: "سفته",          defaultAccount: "اسناد پرداختنی",  isDefault: true },
  { code: "CREDIT", title: "اعتباری",        method: "اعتباری",       defaultAccount: "اعتباری",          isDefault: true },
  { code: "WALLET", title: "کیف پول",        method: "کیف پول",       defaultAccount: "کیف پول",          isDefault: true },
  { code: "OTHER",  title: "سایر",           method: "سایر",          defaultAccount: "سایر",             isDefault: true },
];

// ─── ساختار یک PaymentType ────────────────────────────────────────────────────
interface PaymentType {
  _id?: ObjectId;
  code: string;
  title: string;
  description: string;
  method: string;
  isActive: boolean;
  isDefault: boolean;
  color: string;
  accounting: {
    defaultMainAccount: string;
    defaultMoeinAccount: string;
    defaultDetailAccount: string;
    defaultAccountLabel: string;
  };
  bankSettings: {
    requireBank: boolean;
    requireAccountNumber: boolean;
    requireShebaNumber: boolean;
    requireCardNumber: boolean;
  };
  checkSettings: {
    requireCheckNumber: boolean;
    requireDueDate: boolean;
    requireIssuerName: boolean;
    allowEndorsement: boolean;
  };
  receiptSettings: {
    requireTrackingNumber: boolean;
    requireReceiptImage: boolean;
    requireRRN: boolean;
  };
  usageRestrictions: {
    usableInReceipt: boolean;
    usableInPayment: boolean;
    onlyCashDesk: boolean;
    onlyBank: boolean;
    onlyTreasury: boolean;
  };
  printSettings: {
    printInReceipt: boolean;
    printInInvoice: boolean;
    printInDocument: boolean;
  };
  systemSettings: {
    isDefaultPayment: boolean;
    requireManagerApproval: boolean;
    allowEditAfterPost: boolean;
    autoGenerateDocument: boolean;
  };
  createdAt: string;
  updatedAt: string;
}

// ─── مقدار پیش‌فرض برای PaymentType جدید ─────────────────────────────────────
function defaultPaymentType(partial: Partial<PaymentType> = {}): Omit<PaymentType, "_id"> {
  return {
    code: "", title: "", description: "", method: "نقدی",
    isActive: true, isDefault: false, color: "#6366f1",
    accounting: {
      defaultMainAccount: "", defaultMoeinAccount: "",
      defaultDetailAccount: "", defaultAccountLabel: "",
    },
    bankSettings: {
      requireBank: false, requireAccountNumber: false,
      requireShebaNumber: false, requireCardNumber: false,
    },
    checkSettings: {
      requireCheckNumber: false, requireDueDate: false,
      requireIssuerName: false, allowEndorsement: false,
    },
    receiptSettings: {
      requireTrackingNumber: false, requireReceiptImage: false, requireRRN: false,
    },
    usageRestrictions: {
      usableInReceipt: true, usableInPayment: true,
      onlyCashDesk: false, onlyBank: false, onlyTreasury: false,
    },
    printSettings: {
      printInReceipt: true, printInInvoice: false, printInDocument: true,
    },
    systemSettings: {
      isDefaultPayment: false, requireManagerApproval: false,
      allowEditAfterPost: false, autoGenerateDocument: false,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...partial,
  };
}

// ─── GET /api/payment-types ───────────────────────────────────────────────────
router.get("/", async (c) => {
  try {
    const db = getDb();
    const { search, method, isActive } = c.req.query();

    const filter: any = {};
    if (search) {
      filter.$or = [
        { code:  { $regex: search, $options: "i" } },
        { title: { $regex: search, $options: "i" } },
      ];
    }
    if (method)   filter.method = method;
    if (isActive !== undefined) filter.isActive = isActive === "true";

    const types = await db.collection("payment_types")
      .find(filter).sort({ isDefault: -1, code: 1 }).toArray();

    return c.json({ success: true, data: types });
  } catch (e: any) {
    return c.json({ success: false, message: e.message }, 500);
  }
});

// ─── POST /api/payment-types/seed ────────────────────────────────────────────
router.post("/seed", async (c) => {
  try {
    const db = getDb();
    let seeded = 0;

    for (const pt of DEFAULT_PAYMENT_TYPES) {
      const exists = await db.collection("payment_types").findOne({ code: pt.code });
      if (!exists) {
        await db.collection("payment_types").insertOne(
          defaultPaymentType({
            ...pt,
            isDefault: true,
            accounting: { defaultMainAccount: "", defaultMoeinAccount: "", defaultDetailAccount: "", defaultAccountLabel: pt.defaultAccount },
          })
        );
        seeded++;
      }
    }

    return c.json({ success: true, message: `${seeded} نوع پرداخت پیش‌فرض بارگذاری شد` });
  } catch (e: any) {
    return c.json({ success: false, message: e.message }, 500);
  }
});

// ─── GET /api/payment-types/:id ───────────────────────────────────────────────
router.get("/:id", async (c) => {
  try {
    const id = c.req.param("id");
    const db = getDb();
    const doc = await db.collection("payment_types")
      .findOne({ _id: new ObjectId(id) });
    if (!doc) return c.json({ success: false, message: "نوع پرداخت یافت نشد" }, 404);
    return c.json({ success: true, data: doc });
  } catch (e: any) {
    return c.json({ success: false, message: e.message }, 500);
  }
});

// ─── POST /api/payment-types ──────────────────────────────────────────────────
router.post("/", async (c) => {
  try {
    const body = await c.req.json();
    const db = getDb();

    if (!body.code || !body.title) {
      return c.json({ success: false, message: "کد و عنوان نوع پرداخت الزامی است" }, 400);
    }

    const exists = await db.collection("payment_types").findOne({ code: body.code });
    if (exists) return c.json({ success: false, message: "نوع پرداختی با این کد قبلاً ثبت شده است" }, 400);

    const doc = defaultPaymentType({
      ...body,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
    const result = await db.collection("payment_types").insertOne(doc);

    return c.json({ success: true, data: { ...doc, _id: result.insertedId } }, 201);
  } catch (e: any) {
    return c.json({ success: false, message: e.message }, 500);
  }
});

// ─── PUT /api/payment-types/:id ───────────────────────────────────────────────
router.put("/:id", async (c) => {
  try {
    const id = c.req.param("id");
    const body = await c.req.json();
    const db = getDb();

    if (body.code) {
      const exists = await db.collection("payment_types")
        .findOne({ code: body.code, _id: { $ne: new ObjectId(id) } });
      if (exists) return c.json({ success: false, message: "نوع پرداختی با این کد قبلاً ثبت شده است" }, 400);
    }

    const { _id, ...update } = body;
    const result = await db.collection("payment_types").findOneAndUpdate(
      { _id: new ObjectId(id) },
      { $set: { ...update, updatedAt: new Date().toISOString() } },
      { returnDocument: "after" }
    );

    if (!result) return c.json({ success: false, message: "نوع پرداخت یافت نشد" }, 404);
    return c.json({ success: true, data: result });
  } catch (e: any) {
    return c.json({ success: false, message: e.message }, 500);
  }
});

// ─── PATCH /api/payment-types/:id/toggle ─────────────────────────────────────
router.patch("/:id/toggle", async (c) => {
  try {
    const id = c.req.param("id");
    const db = getDb();
    const current = await db.collection("payment_types").findOne({ _id: new ObjectId(id) });
    if (!current) return c.json({ success: false, message: "نوع پرداخت یافت نشد" }, 404);

    const result = await db.collection("payment_types").findOneAndUpdate(
      { _id: new ObjectId(id) },
      { $set: { isActive: !current.isActive, updatedAt: new Date().toISOString() } },
      { returnDocument: "after" }
    );
    return c.json({ success: true, data: result });
  } catch (e: any) {
    return c.json({ success: false, message: e.message }, 500);
  }
});

// ─── DELETE /api/payment-types/:id ────────────────────────────────────────────
router.delete("/:id", async (c) => {
  try {
    const id = c.req.param("id");
    const db = getDb();

    const payType = await db.collection("payment_types").findOne({ _id: new ObjectId(id) });
    if (!payType) return c.json({ success: false, message: "نوع پرداخت یافت نشد" }, 404);

    // بررسی استفاده در اسناد مالی
    const usedCount = await db.collection("journal_documents")
      .countDocuments({ payment_type_code: payType.code });

    if (usedCount > 0) {
      await db.collection("payment_types").updateOne(
        { _id: new ObjectId(id) },
        { $set: { isActive: false, updatedAt: new Date().toISOString() } }
      );
      return c.json({
        success: true, deactivated: true,
        message: `این نوع پرداخت در ${usedCount} سند مالی استفاده شده است. به‌جای حذف، غیرفعال گردید.`,
      });
    }

    if (payType.isDefault) {
      return c.json({
        success: false,
        message: "انواع پرداخت پیش‌فرض سیستم قابل حذف نیستند. فقط می‌توانید آن‌ها را غیرفعال کنید.",
      }, 400);
    }

    await db.collection("payment_types").deleteOne({ _id: new ObjectId(id) });
    return c.json({ success: true, message: "نوع پرداخت با موفقیت حذف شد" });
  } catch (e: any) {
    return c.json({ success: false, message: e.message }, 500);
  }
});

export default router;
