import BasicInfo from "@/pages/BasicInfo";
import DocumentSetup from "@/pages/DocumentSetup";
import Review from "@/pages/Review";
import Credits from "@/pages/Credits";
import CheckIssuance from "@/pages/CheckIssuance";
import Bookkeeping from "@/pages/Bookkeeping";
import SystemManagement from "@/pages/SystemManagement";
import Guarantees from "@/pages/Guarantees";
import Deposits from "@/pages/Deposits";
import Placeholder from "@/pages/Placeholder";
import { getAllMenuRoutes } from "@/config/navigation";

/** صفحاتی که پیاده‌سازی شده‌اند — بقیه خودکار Placeholder می‌شوند */
export const PAGE_COMPONENTS = {
  "/basic-info": BasicInfo,
  "/basic-info/credits": Credits,
  "/basic-info/document-setup": DocumentSetup,
  "/basic-info/check-issuance": CheckIssuance,
  "/basic-info/bookkeeping": Bookkeeping,
  "/document-setup": DocumentSetup,
  "/review": Review,
  "/credits": Credits,
  "/credits/agreements": Credits,
  "/credits/allocation-no-doc": Credits,
  "/credits/search": Credits,
  "/credits/receipt-no-doc": Credits,
  "/credits/funded": Credits,
  "/credits/funded-search": Credits,
  "/credits/funded-copy": Credits,
  "/credits/funded-merge": Credits,
  "/credits/payroll-from-excel": Credits,
  "/credits/payroll-funding": Credits,
  "/credits/payment-request-no-doc": Credits,
  "/credits/notification": Credits,
  "/credits/notification/request": Credits,
  "/credits/notification/bank-report": Credits,
  "/credits/notification/court-form": Credits,
  "/credits/notification/recipients-report": Credits,
  "/credits/notification/request-report": Credits,
  "/credits/notification/recipients-detail-report": Credits,
  "/credits/notification/fund-confirmation": Credits,
  "/credits/notification/request-report-2": Credits,
  "/credits/notification/supplementary-report": Credits,
  "/credits/notification/copy-request": Credits,
  "/credits/reports": Credits,
  "/credits/reports/budget": Credits,
  "/credits/reports/budget/all-programs": Credits,
  "/credits/reports/budget/program-activities": Credits,
  "/credits/reports/budget/funded-programs": Credits,
  "/credits/reports/budget/dept-by-deputy": Credits,
  "/credits/reports/budget/deputy-activities": Credits,
  "/credits/reports/budget/program-agents": Credits,
  "/credits/reports/budget/program-notif-receivers": Credits,
  "/credits/reports/budget/activity-notif-receivers": Credits,
  "/credits/reports/budget/misc-payments": Credits,
  "/credits/reports/budget/contracts-by-program": Credits,
  "/credits/reports/budget/contract-programs": Credits,
  "/credits/reports/budget/contract-activities": Credits,
  "/credits/reports/budget/contract-sub-activities": Credits,
  "/credits/reports/performance": Credits,
  "/credits/reports/performance/program-stats": Credits,
  "/credits/reports/performance/by-program": Credits,
  "/credits/reports/performance/by-chapter-program": Credits,
  "/credits/reports/performance/by-deputy": Credits,
  "/credits/reports/performance/summary": Credits,
  "/credits/reports/performance/funding": Credits,
  "/credits/reports/performance/by-agent": Credits,
  "/credits/reports/performance/by-notif-receiver": Credits,
  "/credits/reports/ledgers": Credits,
  "/credits/reports/ledgers/program-level": Credits,
  "/credits/reports/ledgers/contract-level": Credits,
  "/credits/reports/ledgers/agent-level": Credits,
  "/credits/reports/ledgers/notif-receiver-level": Credits,
  "/credits/reports/ledgers/misc-level": Credits,
  "/credits/reports/ledgers/interim-docs": Credits,
  "/credits/reports/ledgers/documentary": Credits,
  "/credits/reports/ledgers/petty-cash": Credits,
  "/credits/reports/ledgers/overall": Credits,
  "/credits/reports/agreements": Credits,
  "/credits/reports/agreements/by-detail": Credits,
  "/credits/reports/agreements/by-detail/program": Credits,
  "/credits/reports/agreements/by-detail/activity": Credits,
  "/credits/reports/agreements/by-detail/clause": Credits,
  "/credits/reports/agreements/by-detail/investment-chapters": Credits,
  "/credits/reports/agreements/by-detail/expense-resources": Credits,
  "/credits/reports/agreements/expense-resources": Credits,
  "/credits/reports/agreements/expense-resources/form-2a": Credits,
  "/credits/reports/agreements/expense-resources/form-4-chapters": Credits,
  "/credits/reports/agreements/expense-resources/form-4-personnel": Credits,
  "/credits/reports/agreements/expense-resources/form-5-income": Credits,
  "/credits/reports/agreements/expense-resources/form-1-summary": Credits,
  "/credits/reports/agreements/expense-resources/form-6-manpower": Credits,
  "/credits/reports/agreements/expense-resources/form-4b-non-personnel": Credits,
  "/credits/reports/agreements/expense-resources/form-3-program-activity": Credits,
  "/credits/reports/agreements/expense-resources/form-2b-annual-plan": Credits,
  "/credits/reports/agreements/expense-resources/form-7-provincial": Credits,
  "/credits/reports/agreements/expense-resources/form-2-expense-program": Credits,
  "/credits/reports/agreements/form-four": Credits,
  "/credits/reports/agreements/detailed-budget": Credits,
  "/credits/reports/agreements/payment-control": Credits,
  "/credits/reports/allocation": Credits,
  "/credits/reports/allocation/by-program": Credits,
  "/credits/reports/allocation/all": Credits,
  "/credits/reports/allocation/program-chapter": Credits,
  "/credits/reports/receipts": Credits,
  "/credits/reports/receipts/all": Credits,
  "/credits/reports/receipts/no-program": Credits,
  "/credits/reports/credits-1": Credits,
  "/credits/reports/payment-request-no-doc": Credits,
  "/credits/reports/comprehensive": Credits,
  "/credits/reports/commercial": Credits,
  "/credits/reports/by-detail": Credits,
  "/credits/sub-accountant-agent": Credits,
  "/credits/sub-accountant-agent/version-1": Credits,
  "/credits/sub-accountant-agent/version-1/total-credit-form": Credits,
  "/credits/sub-accountant-agent/version-1/agent-requests": Credits,
  "/credits/sub-accountant-agent/version-1/agent-expenses": Credits,
  "/credits/sub-accountant-agent/version-1/fund-from-expense": Credits,
  "/credits/sub-accountant-agent/version-2": Credits,
  "/credits/sub-accountant-agent/version-2/send-credit": Credits,
  "/credits/sub-accountant-agent/version-2/confirm-issue": Credits,
  "/credits/sub-accountant-agent/view-confirm-credit": Credits,
  "/credits/sub-accountant-agent/view-confirm-request": Credits,
  "/credits/sub-accountant-agent/view-confirm-expense": Credits,
  "/credits/sub-accountant-agent/plan-program-percent": Credits,
  "/credits/sub-accountant-agent/cost-center-relation": Credits,
  "/credits/sub-accountant-agent/agents-relation": Credits,
  "/credits/read-from-file": Credits,
  "/credits/warehouse-receipt-reg": Credits,
  "/credits/fund-from-doc": Credits,
  "/credits/warehouse-fund-template": Credits,
  "/check-issuance": CheckIssuance,
  "/check-issuance/receipts": CheckIssuance,
  "/check-issuance/receipts/check-issuance": CheckIssuance,
  "/check-issuance/payments": CheckIssuance,
  "/check-issuance/payments/with-check": CheckIssuance,
  "/check-issuance/payments/without-check": CheckIssuance,
  "/check-issuance/payments/cancel-check": CheckIssuance,
  "/check-issuance/payments/return-voided": CheckIssuance,
  "/check-issuance/payments/cancel-without-check": CheckIssuance,
  "/check-issuance/payments/check-delivery": CheckIssuance,
  "/check-issuance/payments/check-toggle": CheckIssuance,
  "/check-issuance/payments/void-no-doc": CheckIssuance,
  "/check-issuance/payments/return-issued": CheckIssuance,
  "/check-issuance/payments/confirm-no-check-payment": CheckIssuance,
  "/check-issuance/payments/aggregate-check": CheckIssuance,
  "/check-issuance/payments/assign-no-doc": CheckIssuance,
  "/check-issuance/payments/print-receipt": CheckIssuance,
  "/check-issuance/payments/register-bank-receipt": CheckIssuance,
  "/check-issuance/payments/print-aggregate-confirmation": CheckIssuance,
  "/check-issuance/reports": CheckIssuance,
  "/check-issuance/reports/bank-ledgers": CheckIssuance,
  "/check-issuance/reports/bank-ledgers/regular": CheckIssuance,
  "/check-issuance/reports/bank-ledgers/detailed": CheckIssuance,
  "/check-issuance/reports/balances": CheckIssuance,
  "/check-issuance/reports/bank-accounts": CheckIssuance,
  "/check-issuance/reports/used-checks": CheckIssuance,
  "/check-issuance/reports/remaining-checks": CheckIssuance,
  "/check-issuance/reports/voided-checks": CheckIssuance,
  "/check-issuance/reports/checkbooks": CheckIssuance,
  "/check-issuance/reports/misc-search": CheckIssuance,
  "/check-issuance/reports/aggregate-checks": CheckIssuance,
  "/check-issuance/reports/aggregate-with-doc": CheckIssuance,
  "/check-issuance/e-transfer": CheckIssuance,
  "/check-issuance/e-transfer-batch": CheckIssuance,
  "/bookkeeping": Bookkeeping,
  "/bookkeeping/operations-balance": Bookkeeping,
  "/bookkeeping/operations-balance/different-states": Bookkeeping,
  "/bookkeeping/operations-balance/moein-chapters": Bookkeeping,
  "/bookkeeping/operations-balance/moein-detail-link": Bookkeeping,
  "/bookkeeping/operations-balance/samad-system": Bookkeeping,
  "/bookkeeping/operations-balance/sanama-attachments": Bookkeeping,
  "/bookkeeping/misc-accounts": Bookkeeping,
  "/bookkeeping/misc-accounts/account-groups": Bookkeeping,
  "/bookkeeping/misc-accounts/main-accounts": Bookkeeping,
  "/bookkeeping/misc-accounts/moein-accounts": Bookkeeping,
  "/bookkeeping/misc-accounts/detail-accounts": Bookkeeping,
  "/bookkeeping/misc-accounts/detailed-report": Bookkeeping,
  "/bookkeeping/bank-reconciliation": Bookkeeping,
  "/bookkeeping/bank-reconciliation/account-format-setup": Bookkeeping,
  "/bookkeeping/bank-reconciliation/account-info-read": Bookkeeping,
  "/bookkeeping/bank-reconciliation/account-reconciliation": Bookkeeping,
  "/bookkeeping/ledger-reports": Bookkeeping,
  "/bookkeeping/final-documents/finalize-doc": Bookkeeping,
  "/bookkeeping/final-documents/unfinalize-doc": Bookkeeping,
  "/bookkeeping/budget-execution": Bookkeeping,
  "/bookkeeping/budget-execution/budget-allocation-setup": Bookkeeping,
  "/bookkeeping/budget-execution/budget-allocation": Bookkeeping,
  "/bookkeeping/budget-execution/aggregate-budget-allocation": Bookkeeping,
  "/bookkeeping/misc-persons": Bookkeeping,
  "/bookkeeping/misc-persons/persons-report": Bookkeeping,
  "/bookkeeping/misc-persons/persons-balance": Bookkeeping,
  "/bookkeeping/financial-statements": Bookkeeping,
  "/bookkeeping/financial-statements/balance-sheet": Bookkeeping,
  "/bookkeeping/financial-statements/change-in-financial-position": Bookkeeping,
  "/bookkeeping/financial-statements/comparison-budget-performance": Bookkeeping,
  "/bookkeeping/financial-statements/parametric-balance-sheet": Bookkeeping,
  "/bookkeeping/financial-statements/notes": Bookkeeping,
  "/bookkeeping/financial-statements/reports-settings": Bookkeeping,
  "/bookkeeping/accountant-agents": Bookkeeping,
  "/bookkeeping/document-notification": Bookkeeping,
  "/bookkeeping/smart-control": Bookkeeping,
  "/bookkeeping/petty-cash": Bookkeeping,
  "/bookkeeping/open-items": Bookkeeping,
  "/bookkeeping/resource-forms": Bookkeeping,
  "/bookkeeping/resource-forms/deposit-expense-confirmation": Bookkeeping,
  "/system-management": SystemManagement,
  "/system-management/automatic-doc-types": SystemManagement,
  "/system-management/non-calc-doc-types": SystemManagement,
  "/system-management/credit-payroll-template": SystemManagement,
  "/system-management/payroll-doc-template": SystemManagement,
  "/system-management/assets-doc-template": SystemManagement,
  "/system-management/calc-formulas": SystemManagement,
  "/system-management/balance-control": SystemManagement,
  "/system-management/credit-control": SystemManagement,
  "/system-management/program-details": SystemManagement,
  "/system-management/user-groups": SystemManagement,
  "/system-management/users": SystemManagement,
  "/system-management/permissions": SystemManagement,
  "/system-management/change-password": SystemManagement,
  "/system-management/user-performance": SystemManagement,
  "/system-management/financial-details": SystemManagement,
  "/system-management/approve-docs": SystemManagement,
  "/system-management/close-account-chapters": SystemManagement,
  "/system-management/settings": SystemManagement,
  "/system-management/update-manager": SystemManagement,
  "/system-management/backup": SystemManagement,
  "/system-management/report-signature": SystemManagement,
  "/system-management/report-generator": SystemManagement,
  "/system-management/person-chapters": SystemManagement,
  "/system-management/revoke-reconciliation": SystemManagement,
  "/system-management/user-circle": SystemManagement,
  "/system-management/revoke-sanama": SystemManagement,
  "/system-management/signature-group": SystemManagement,
  "/system-management/convert-chapter95": SystemManagement,
  "/system-management/convert-chapter94": SystemManagement,
  "/system-management/common-settings": SystemManagement,
  "/system-management/change-moein-doc": SystemManagement,
  "/system-management/cartable": SystemManagement,
  "/system-management/credit-settings": SystemManagement,
  "/system-management/revoke-e-transfer": SystemManagement,
  "/system-management/sanama-file-check": SystemManagement,
  "/system-management/doc-requirements": SystemManagement,
  "/guarantees": Guarantees,
  "/deposits": Deposits,
};

export function buildLayoutRoutes(HomePage) {
  const menuRoutes = getAllMenuRoutes();
  const routes = [{ path: "/", element: <HomePage /> }];

  for (const { path, label } of menuRoutes) {
    const Component = PAGE_COMPONENTS[path];
    routes.push({
      path,
      element: Component ? <Component /> : <Placeholder label={label} />,
    });
  }

  return routes;
}
