import BasicInfo from "@/pages/BasicInfo";
import DocumentSetup from "@/pages/DocumentSetup";
import Review from "@/pages/Review";
import Credits from "@/pages/Credits";
import CheckIssuance from "@/pages/CheckIssuance";
import Bookkeeping from "@/pages/Bookkeeping";
import SystemManagement from "@/pages/SystemManagement";
import Guarantees from "@/pages/Guarantees";
import Deposits from "@/pages/Deposits";
import Placeholder from "@/pages/Placeholder";
import { getAllMenuRoutes } from "@/config/navigation";

/** صفحاتی که پیاده‌سازی شده‌اند — بقیه خودکار Placeholder می‌شوند */
export const PAGE_COMPONENTS = {
  "/basic-info": BasicInfo,
  "/basic-info/credits": Credits,
  "/basic-info/document-setup": DocumentSetup,
  "/basic-info/check-issuance": CheckIssuance,
  "/basic-info/bookkeeping": Bookkeeping,
  "/document-setup": DocumentSetup,
  "/review": Review,
  "/credits": Credits,
  "/credits/agreements": Credits,
  "/credits/allocation-no-doc": Credits,
  "/credits/search": Credits,
  "/credits/receipt-no-doc": Credits,
  "/credits/funded": Credits,
  "/credits/funded-search": Credits,
  "/credits/funded-copy": Credits,
  "/credits/funded-merge": Credits,
  "/credits/payroll-from-excel": Credits,
  "/credits/payroll-funding": Credits,
  "/credits/payment-request-no-doc": Credits,
  "/credits/notification": Credits,
  "/credits/notification/request": Credits,
  "/credits/notification/bank-report": Credits,
  "/credits/notification/court-form": Credits,
  "/credits/notification/recipients-report": Credits,
  "/credits/notification/request-report": Credits,
  "/credits/notification/recipients-detail-report": Credits,
  "/credits/notification/fund-confirmation": Credits,
  "/credits/notification/request-report-2": Credits,
  "/credits/notification/supplementary-report": Credits,
  "/credits/notification/copy-request": Credits,
  "/credits/reports": Credits,
  "/credits/reports/budget": Credits,
  "/credits/reports/budget/all-programs": Credits,
  "/credits/reports/budget/program-activities": Credits,
  "/credits/reports/budget/funded-programs": Credits,
  "/credits/reports/budget/dept-by-deputy": Credits,
  "/credits/reports/budget/deputy-activities": Credits,
  "/credits/reports/budget/program-agents": Credits,
  "/credits/reports/budget/program-notif-receivers": Credits,
  "/credits/reports/budget/activity-notif-receivers": Credits,
  "/credits/reports/budget/misc-payments": Credits,
  "/credits/reports/budget/contracts-by-program": Credits,
  "/credits/reports/budget/contract-programs": Credits,
  "/credits/reports/budget/contract-activities": Credits,
  "/credits/reports/budget/contract-sub-activities": Credits,
  "/credits/reports/performance": Credits,
  "/credits/reports/performance/program-stats": Credits,
  "/credits/reports/performance/by-program": Credits,
  "/credits/reports/performance/by-chapter-program": Credits,
  "/credits/reports/performance/by-deputy": Credits,
  "/credits/reports/performance/summary": Credits,
  "/credits/reports/performance/funding": Credits,
  "/credits/reports/performance/by-agent": Credits,
  "/credits/reports/performance/by-notif-receiver": Credits,
  "/credits/reports/ledgers": Credits,
  "/credits/reports/ledgers/program-level": Credits,
  "/credits/reports/ledgers/contract-level": Credits,
  "/credits/reports/ledgers/agent-level": Credits,
  "/credits/reports/ledgers/notif-receiver-level": Credits,
  "/credits/reports/ledgers/misc-level": Credits,
  "/credits/reports/ledgers/interim-docs": Credits,
  "/credits/reports/ledgers/documentary": Credits,
  "/credits/reports/ledgers/petty-cash": Credits,
  "/credits/reports/ledgers/overall": Credits,
  "/credits/reports/agreements": Credits,
  "/credits/reports/agreements/by-detail": Credits,
  "/credits/reports/agreements/by-detail/program": Credits,
  "/credits/reports/agreements/by-detail/activity": Credits,
  "/credits/reports/agreements/by-detail/clause": Credits,
  "/credits/reports/agreements/by-detail/investment-chapters": Credits,
  "/credits/reports/agreements/by-detail/expense-resources": Credits,
  "/credits/reports/agreements/expense-resources": Credits,
  "/credits/reports/agreements/expense-resources/form-2a": Credits,
  "/credits/reports/agreements/expense-resources/form-4-chapters": Credits,
  "/credits/reports/agreements/expense-resources/form-4-personnel": Credits,
  "/credits/reports/agreements/expense-resources/form-5-income": Credits,
  "/credits/reports/agreements/expense-resources/form-1-summary": Credits,
  "/credits/reports/agreements/expense-resources/form-6-manpower": Credits,
  "/credits/reports/agreements/expense-resources/form-4b-non-personnel": Credits,
  "/credits/reports/agreements/expense-resources/form-3-program-activity": Credits,
  "/credits/reports/agreements/expense-resources/form-2b-annual-plan": Credits,
  "/credits/reports/agreements/expense-resources/form-7-provincial": Credits,
  "/credits/reports/agreements/expense-resources/form-2-expense-program": Credits,
  "/credits/reports/agreements/form-four": Credits,
  "/credits/reports/agreements/detailed-budget": Credits,
  "/credits/reports/agreements/payment-control": Credits,
  "/credits/reports/allocation": Credits,
  "/credits/reports/allocation/by-program": Credits,
  "/credits/reports/allocation/all": Credits,
  "/credits/reports/allocation/program-chapter": Credits,
  "/credits/reports/receipts": Credits,
  "/credits/reports/receipts/all": Credits,
  "/credits/reports/receipts/no-program": Credits,
  "/credits/reports/credits-1": Credits,
  "/credits/reports/payment-request-no-doc": Credits,
  "/credits/reports/comprehensive": Credits,
  "/credits/reports/commercial": Credits,
  "/credits/reports/by-detail": Credits,
  "/credits/sub-accountant-agent": Credits,
  "/credits/sub-accountant-agent/version-1": Credits,
  "/credits/sub-accountant-agent/version-1/total-credit-form": Credits,
  "/credits/sub-accountant-agent/version-1/agent-requests": Credits,
  "/credits/sub-accountant-agent/version-1/agent-expenses": Credits,
  "/credits/sub-accountant-agent/version-1/fund-from-expense": Credits,
  "/credits/sub-accountant-agent/version-2": Credits,
  "/credits/sub-accountant-agent/version-2/send-credit": Credits,
  "/credits/sub-accountant-agent/version-2/confirm-issue": Credits,
  "/credits/sub-accountant-agent/view-confirm-credit": Credits,
  "/credits/sub-accountant-agent/view-confirm-request": Credits,
  "/credits/sub-accountant-agent/view-confirm-expense": Credits,
  "/credits/sub-accountant-agent/plan-program-percent": Credits,
  "/credits/sub-accountant-agent/cost-center-relation": Credits,
  "/credits/sub-accountant-agent/agents-relation": Credits,
  "/credits/read-from-file": Credits,
  "/credits/warehouse-receipt-reg": Credits,
  "/credits/fund-from-doc": Credits,
  "/credits/warehouse-fund-template": Credits,
  "/check-issuance": CheckIssuance,
  "/bookkeeping": Bookkeeping,
  "/system-management": SystemManagement,
  "/guarantees": Guarantees,
  "/deposits": Deposits,
};

export function buildLayoutRoutes(HomePage) {
  const menuRoutes = getAllMenuRoutes();
  const routes = [{ path: "/", element: <HomePage /> }];

  for (const { path, label } of menuRoutes) {
    const Component = PAGE_COMPONENTS[path];
    routes.push({
      path,
      element: Component ? <Component /> : <Placeholder label={label} />,
    });
  }

  return routes;
}
