export const SANAMA_CONSTANTS = {
  PROTOCOL_NAME: "SANAMA",
  PROTOCOL_VER: "3.2", // Protocol Version 3.2 - Edition 19
  EDITION: "19",
  
  MONTH_MAP: {
    "1": "فروردین",
    "2": "اردیبهشت",
    "3": "خرداد",
    "4": "تیر",
    "5": "مرداد",
    "6": "شهریور",
    "7": "مهر",
    "8": "آبان",
    "9": "آذر",
    "10": "دی",
    "11": "بهمن",
    "12": "اسفند",
    "15": "تراز نهایی سال مالی"
  } as Record<string, string>,

  // List of all 54 attribute names in canonical order according to SANAMA Edition 19 Section 4
  ATTRIBUTES: [
    "SourceType", "SourceEssence", "OtherSourceType", "CreditType", "TransferalType",
    "CreditInfo", "RankNumber", "CreditCode", "ExpenseArticle", "ConstructArticle",
    "ExpenseDetailArticle", "IncomeCode", "IncomeSubject", "IncomesSubject", "Governmental", "TaxSeason", "DebentureSenderRank",
    "DebentureReceiverRank", "CostCenter", "AwardArticle", "SecuritiesType", "Year",
    "NomineeCode", "Nominee", "GuaranteeEssence", "DemandStatus", "TempPaymentType",
    "LeakageSubject", "AssuranceType", "AssuranceSubject", "CurrencyType", "AccountNumber",
    "InsuranceType", "DebitSubject", "FixedAssetType", "InventoryType", "Quantity",
    "DueDate", "SecuritiesProperties", "ContractProperties", "InvestmentType",
    "AnnualAdjustmentsSubject", "AnnualAdjustmentSubject", "TransferItems", "ReceivablesSubject", "AllocationSource", "AllocationsSource",
    "SubBudgetCode", "ExpensePart", "ExpenseKind", "ExecutiveUnit", "Output"
  ],

  // Mapping attribute name to requirement row index in sanamaRequirements.json
  ATTR_TO_ROW_MAP: {
    SourceType: 1,
    SourceEssence: 2,
    OtherSourceType: 3,
    CreditType: 4,
    TransferalType: 5,
    CreditInfo: 6,
    RankNumber: 7,
    CreditCode: 8,
    ExpenseArticle: 10,
    ConstructArticle: 11,
    ExpenseDetailArticle: 12,
    IncomeCode: 13,
    IncomeSubject: 14,
    IncomesSubject: 14,
    Governmental: 15,
    TaxSeason: 16,
    DebentureSenderRank: 17,
    DebentureReceiverRank: 18,
    CostCenter: 19,
    AwardArticle: 20,
    SecuritiesType: 21,
    Year: 22,
    NomineeCode: 23,
    Nominee: 24,
    GuaranteeEssence: 25,
    DemandStatus: 26,
    TempPaymentType: 27,
    LeakageSubject: 28,
    AssuranceType: 29,
    AssuranceSubject: 30,
    CurrencyType: 31,
    AccountNumber: 32,
    InsuranceType: 33,
    DebitSubject: 34,
    FixedAssetType: 35,
    InventoryType: 36,
    Quantity: 37,
    DueDate: 38,
    SecuritiesProperties: 39,
    ContractProperties: 40,
    InvestmentType: 41,
    AnnualAdjustmentsSubject: 42,
    AnnualAdjustmentSubject: 42,
    TransferItems: 43,
    ReceivablesSubject: 44,
    AllocationSource: 45,
    AllocationsSource: 45,
    SubBudgetCode: 46,
    ExpensePart: 47,
    ExpenseKind: 48,
    ExecutiveUnit: 49,
    Output: 50
  } as Record<string, number>,

  DEFAULT_VALUES: {
    SourceType: "0",
    SourceEssence: "0",
    OtherSourceType: "0",
    CreditType: "",
    TransferalType: "0",
    CreditInfo: "0",
    RankNumber: "0",
    CreditCode: "0",
    ExpenseArticle: "0",
    ConstructArticle: "0",
    ExpenseDetailArticle: "0",
    IncomeCode: "0",
    IncomeSubject: "0",
    IncomesSubject: "0",
    Governmental: "0",
    TaxSeason: "0",
    DebentureSenderRank: "",
    DebentureReceiverRank: "0",
    CostCenter: "",
    Year: "1403",
    NomineeCode: "0",
    Nominee: "0",
    GuaranteeEssence: "0",
    DemandStatus: "0",
    TempPaymentType: "0",
    LeakageSubject: "0",
    AssuranceType: "0",
    AssuranceSubject: "0",
    CurrencyType: "0",
    AccountNumber: "IR0",
    InsuranceType: "0",
    DebitSubject: "0",
    FixedAssetType: "0",
    InventoryType: "0",
    Quantity: "0",
    DueDate: "0",
    SecuritiesProperties: "0",
    ContractProperties: "0",
    InvestmentType: "0",
    AnnualAdjustmentsSubject: "0",
    AnnualAdjustmentSubject: "0",
    TransferItems: "0",
    ReceivablesSubject: "0",
    AllocationSource: "0",
    AllocationsSource: "0",
    SubBudgetCode: "400367",
    ExpensePart: "0",
    ExpenseKind: "0",
    ExecutiveUnit: "0",
    Output: "0"
  } as Record<string, string>,

  // Enum validations for specific SANAMA fields
  SOURCE_TYPES: ["1", "2", "3"], // 1=عمومی, 2=اختصاصی, 3=سایر
  SOURCE_ESSENCES: ["1", "2", "3"], // 1=درآمد, 2=واگذاری دارایی‌های سرمایه‌ای, 3=واگذاری دارایی‌های مالی
  CREDIT_TYPES: ["1", "2"], // 1=مصوب, 2=ابلاغی
  TRANSFERAL_TYPES: ["1", "2", "3"], // 1=سال جاری, 2=دوره متمم, 3=سنواتی
  CREDIT_INFOS: ["1", "2"], // 1=برنامه, 2=طرح

  ALLOWED_ATTACHMENT_EXTENSIONS: [".jpg", ".jpeg", ".png", ".tif", ".tiff", ".gif", ".doc", ".docx", ".pdf"]
};
