import { useState, useEffect, useCallback, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { PageShell, PageHeader } from "@/components/layout/PageShell";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Plus, Search, Trash2, Pencil, RefreshCw, X, CheckCircle2, XCircle,
  Eye, Power, Info, CreditCard, Building2, FileCheck, Settings2,
  Printer, Download, Wallet, Shield,
} from "lucide-react";
import api from "@/api";

// ─── ثابت‌ها ───────────────────────────────────────────────────────────────────
const METHODS = [
  "نقدی", "کارتخوان", "کارت به کارت", "حواله بانکی",
  "پایا", "ساتنا", "اینترنتی", "چک", "سفته",
  "اعتباری", "کیف پول", "سایر",
];

const METHOD_COLORS = {
  "نقدی":          "bg-emerald-100 text-emerald-700",
  "کارتخوان":      "bg-blue-100 text-blue-700",
  "کارت به کارت":  "bg-sky-100 text-sky-700",
  "حواله بانکی":   "bg-indigo-100 text-indigo-700",
  "پایا":          "bg-violet-100 text-violet-700",
  "ساتنا":         "bg-purple-100 text-purple-700",
  "اینترنتی":      "bg-cyan-100 text-cyan-700",
  "چک":            "bg-amber-100 text-amber-700",
  "سفته":          "bg-orange-100 text-orange-700",
  "اعتباری":       "bg-rose-100 text-rose-700",
  "کیف پول":       "bg-pink-100 text-pink-700",
  "سایر":          "bg-gray-100 text-gray-700",
};

const BANK_METHODS = ["کارتخوان", "کارت به کارت", "حواله بانکی", "پایا", "ساتنا", "اینترنتی"];
const CHECK_METHODS = ["چک", "سفته"];

// ─── مقدار پیش‌فرض فرم ────────────────────────────────────────────────────────
const emptyForm = () => ({
  code: "", title: "", description: "", method: "نقدی",
  isActive: true, isDefault: false, color: "#6366f1",
  accounting: {
    defaultMainAccount: "", defaultMoeinAccount: "",
    defaultDetailAccount: "", defaultAccountLabel: "",
  },
  bankSettings: {
    requireBank: false, requireAccountNumber: false,
    requireShebaNumber: false, requireCardNumber: false,
  },
  checkSettings: {
    requireCheckNumber: false, requireDueDate: false,
    requireIssuerName: false, allowEndorsement: false,
  },
  receiptSettings: {
    requireTrackingNumber: false, requireReceiptImage: false, requireRRN: false,
  },
  usageRestrictions: {
    usableInReceipt: true, usableInPayment: true,
    onlyCashDesk: false, onlyBank: false, onlyTreasury: false,
  },
  printSettings: {
    printInReceipt: true, printInInvoice: false, printInDocument: true,
  },
  systemSettings: {
    isDefaultPayment: false, requireManagerApproval: false,
    allowEditAfterPost: false, autoGenerateDocument: false,
  },
});

// ─── کامپوننت‌های کمکی ─────────────────────────────────────────────────────────
function SectionTitle({ icon: Icon, title, color = "text-primary" }) {
  return (
    <div className={`flex items-center gap-2 mb-3 pb-2 border-b font-bold text-sm ${color}`}>
      <Icon className="h-4 w-4" />{title}
    </div>
  );
}

function Field({ label, children, required }) {
  return (
    <div className="space-y-1">
      <Label className="text-xs font-medium text-foreground/80">
        {label}{required && <span className="text-destructive mr-0.5">*</span>}
      </Label>
      {children}
    </div>
  );
}

function Sel({ value, onChange, options, placeholder }) {
  return (
    <select
      value={value}
      onChange={(e) => onChange(e.target.value)}
      className="w-full h-9 text-sm rounded-md border border-input bg-background px-2.5 focus:outline-none focus:ring-1 focus:ring-primary"
    >
      {placeholder && <option value="">{placeholder}</option>}
      {options.map((o) =>
        typeof o === "string"
          ? <option key={o} value={o}>{o}</option>
          : <option key={o.value} value={o.value}>{o.label}</option>
      )}
    </select>
  );
}

function CheckItem({ label, checked, onChange, description }) {
  return (
    <label className="flex items-start gap-2.5 cursor-pointer group py-1">
      <input
        type="checkbox"
        checked={checked}
        onChange={(e) => onChange(e.target.checked)}
        className="mt-0.5 h-4 w-4 rounded border-input text-primary focus:ring-primary shrink-0"
      />
      <div>
        <span className="text-sm group-hover:text-foreground text-foreground/80">{label}</span>
        {description && <p className="text-[11px] text-muted-foreground mt-0.5">{description}</p>}
      </div>
    </label>
  );
}

function Toast({ toast, onClose }) {
  useEffect(() => {
    if (!toast) return;
    const t = setTimeout(onClose, 3200);
    return () => clearTimeout(t);
  }, [toast, onClose]);

  return (
    <AnimatePresence>
      {toast && (
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 30 }}
          className={`fixed bottom-6 left-1/2 -translate-x-1/2 z-[200] flex items-center gap-2 px-5 py-3 rounded-xl shadow-xl text-sm font-medium
            ${toast.type === "error" ? "bg-destructive text-destructive-foreground" : "bg-emerald-600 text-white"}`}
        >
          {toast.type === "error" ? <XCircle className="h-4 w-4 shrink-0" /> : <CheckCircle2 className="h-4 w-4 shrink-0" />}
          {toast.msg}
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// ─── بخش ۱: اطلاعات اصلی ──────────────────────────────────────────────────────
function Section1({ form, set, codeRef }) {
  return (
    <div className="space-y-4">
      <SectionTitle icon={Info} title="اطلاعات اصلی" />
      <div className="grid grid-cols-2 gap-3">
        <Field label="کد پرداخت" required>
          <Input
            ref={codeRef}
            value={form.code}
            onChange={(e) => set("code", e.target.value.toUpperCase())}
            placeholder="مثال: CASH"
            className="h-9 font-mono tracking-widest"
            maxLength={10}
          />
        </Field>
        <Field label="وضعیت">
          <div className="flex items-center gap-2 h-9">
            <input
              type="checkbox"
              id="isActive"
              checked={form.isActive}
              onChange={(e) => set("isActive", e.target.checked)}
              className="h-4 w-4 rounded"
            />
            <Label htmlFor="isActive" className="text-sm cursor-pointer">فعال</Label>
          </div>
        </Field>
      </div>
      <Field label="عنوان نوع پرداخت" required>
        <Input
          value={form.title}
          onChange={(e) => set("title", e.target.value)}
          placeholder="مثال: کارتخوان بانک ملی"
          className="h-9"
        />
      </Field>
      <Field label="شرح">
        <textarea
          value={form.description}
          onChange={(e) => set("description", e.target.value)}
          rows={2}
          placeholder="توضیحات تکمیلی..."
          className="w-full text-sm rounded-md border border-input bg-background px-3 py-2 focus:outline-none focus:ring-1 focus:ring-primary resize-none"
        />
      </Field>
      <div className="grid grid-cols-2 gap-3">
        <Field label="نحوه پرداخت">
          <Sel value={form.method} onChange={(v) => set("method", v)} options={METHODS} />
        </Field>
        <Field label="رنگ نمایش">
          <div className="flex items-center gap-2 h-9">
            <input
              type="color"
              value={form.color}
              onChange={(e) => set("color", e.target.value)}
              className="h-8 w-8 rounded border cursor-pointer"
            />
            <span className="text-xs font-mono text-muted-foreground">{form.color}</span>
          </div>
        </Field>
      </div>
    </div>
  );
}

// ─── بخش ۲: تنظیمات حسابداری ──────────────────────────────────────────────────
function Section2({ form, set }) {
  return (
    <div className="space-y-4">
      <SectionTitle icon={Building2} title="تنظیمات حسابداری" color="text-emerald-600" />
      <div className="grid grid-cols-2 gap-3">
        <Field label="حساب کل پیش‌فرض">
          <Input
            value={form.accounting.defaultMainAccount}
            onChange={(e) => set("accounting.defaultMainAccount", e.target.value)}
            placeholder="کد یا نام حساب کل"
            className="h-9"
          />
        </Field>
        <Field label="حساب معین پیش‌فرض">
          <Input
            value={form.accounting.defaultMoeinAccount}
            onChange={(e) => set("accounting.defaultMoeinAccount", e.target.value)}
            placeholder="کد یا نام حساب معین"
            className="h-9"
          />
        </Field>
        <Field label="حساب تفصیلی پیش‌فرض">
          <Input
            value={form.accounting.defaultDetailAccount}
            onChange={(e) => set("accounting.defaultDetailAccount", e.target.value)}
            placeholder="اختیاری"
            className="h-9"
          />
        </Field>
        <Field label="نام نمایشی حساب">
          <Input
            value={form.accounting.defaultAccountLabel}
            onChange={(e) => set("accounting.defaultAccountLabel", e.target.value)}
            placeholder="مثلاً صندوق، بانک ملی"
            className="h-9"
          />
        </Field>
      </div>
      <div className="flex items-start gap-2 bg-blue-50 border border-blue-100 rounded-lg px-3 py-2.5 text-xs text-blue-700">
        <Info className="h-3.5 w-3.5 mt-0.5 shrink-0" />
        این حساب‌ها هنگام تولید خودکار سند حسابداری استفاده می‌شوند
      </div>
    </div>
  );
}

// ─── بخش ۳: الزامات ثبت ───────────────────────────────────────────────────────
function Section3({ form, set }) {
  const showBank  = BANK_METHODS.includes(form.method);
  const showCheck = CHECK_METHODS.includes(form.method);

  return (
    <div className="space-y-5">
      <SectionTitle icon={FileCheck} title="الزامات ثبت" color="text-violet-600" />

      {showBank && (
        <div>
          <p className="text-xs font-semibold text-muted-foreground mb-2">تنظیمات بانکی</p>
          <div className="grid grid-cols-2 gap-x-6 gap-y-0">
            <CheckItem label="الزام انتخاب بانک"       checked={form.bankSettings.requireBank}          onChange={(v) => set("bankSettings.requireBank", v)} />
            <CheckItem label="الزام شماره حساب"        checked={form.bankSettings.requireAccountNumber} onChange={(v) => set("bankSettings.requireAccountNumber", v)} />
            <CheckItem label="الزام شماره شبا"         checked={form.bankSettings.requireShebaNumber}   onChange={(v) => set("bankSettings.requireShebaNumber", v)} />
            <CheckItem label="الزام شماره کارت"        checked={form.bankSettings.requireCardNumber}    onChange={(v) => set("bankSettings.requireCardNumber", v)} />
          </div>
        </div>
      )}

      {showCheck && (
        <div>
          <p className="text-xs font-semibold text-muted-foreground mb-2">تنظیمات چک / سفته</p>
          <div className="grid grid-cols-2 gap-x-6 gap-y-0">
            <CheckItem label="الزام شماره چک"          checked={form.checkSettings.requireCheckNumber} onChange={(v) => set("checkSettings.requireCheckNumber", v)} />
            <CheckItem label="الزام تاریخ سررسید"      checked={form.checkSettings.requireDueDate}     onChange={(v) => set("checkSettings.requireDueDate", v)} />
            <CheckItem label="الزام نام صادرکننده"     checked={form.checkSettings.requireIssuerName}  onChange={(v) => set("checkSettings.requireIssuerName", v)} />
            <CheckItem label="امکان ظهرنویسی"          checked={form.checkSettings.allowEndorsement}   onChange={(v) => set("checkSettings.allowEndorsement", v)} />
          </div>
        </div>
      )}

      <div>
        <p className="text-xs font-semibold text-muted-foreground mb-2">تنظیمات رسید</p>
        <div className="grid grid-cols-2 gap-x-6 gap-y-0">
          <CheckItem label="الزام کد رهگیری"           checked={form.receiptSettings.requireTrackingNumber} onChange={(v) => set("receiptSettings.requireTrackingNumber", v)} />
          <CheckItem label="الزام تصویر رسید"          checked={form.receiptSettings.requireReceiptImage}   onChange={(v) => set("receiptSettings.requireReceiptImage", v)} />
          <CheckItem label="الزام شماره RRN"           checked={form.receiptSettings.requireRRN}            onChange={(v) => set("receiptSettings.requireRRN", v)} />
        </div>
      </div>
    </div>
  );
}

// ─── بخش ۴: تنظیمات و محدودیت‌ها ─────────────────────────────────────────────
function Section4({ form, set }) {
  return (
    <div className="space-y-5">
      <SectionTitle icon={Settings2} title="تنظیمات و محدودیت‌ها" color="text-rose-600" />

      <div>
        <p className="text-xs font-semibold text-muted-foreground mb-2">موارد استفاده</p>
        <div className="grid grid-cols-2 gap-x-6 gap-y-0">
          <CheckItem label="قابل استفاده در دریافت"   checked={form.usageRestrictions.usableInReceipt}  onChange={(v) => set("usageRestrictions.usableInReceipt", v)} />
          <CheckItem label="قابل استفاده در پرداخت"   checked={form.usageRestrictions.usableInPayment}  onChange={(v) => set("usageRestrictions.usableInPayment", v)} />
        </div>
      </div>

      <div>
        <p className="text-xs font-semibold text-muted-foreground mb-2">محدودیت‌های استفاده</p>
        <div className="grid grid-cols-2 gap-x-6 gap-y-0">
          <CheckItem label="فقط صندوق"                checked={form.usageRestrictions.onlyCashDesk}     onChange={(v) => set("usageRestrictions.onlyCashDesk", v)} />
          <CheckItem label="فقط بانک"                 checked={form.usageRestrictions.onlyBank}         onChange={(v) => set("usageRestrictions.onlyBank", v)} />
          <CheckItem label="فقط خزانه"                checked={form.usageRestrictions.onlyTreasury}     onChange={(v) => set("usageRestrictions.onlyTreasury", v)} />
        </div>
      </div>

      <div>
        <p className="text-xs font-semibold text-muted-foreground mb-2 flex items-center gap-1.5"><Printer className="h-3.5 w-3.5" />تنظیمات چاپ</p>
        <div className="grid grid-cols-2 gap-x-6 gap-y-0">
          <CheckItem label="چاپ در رسید"              checked={form.printSettings.printInReceipt}    onChange={(v) => set("printSettings.printInReceipt", v)} />
          <CheckItem label="چاپ در فاکتور"            checked={form.printSettings.printInInvoice}    onChange={(v) => set("printSettings.printInInvoice", v)} />
          <CheckItem label="چاپ در سند"               checked={form.printSettings.printInDocument}   onChange={(v) => set("printSettings.printInDocument", v)} />
        </div>
      </div>

      <div>
        <p className="text-xs font-semibold text-muted-foreground mb-2 flex items-center gap-1.5"><Shield className="h-3.5 w-3.5" />تنظیمات سیستم</p>
        <div className="grid grid-cols-2 gap-x-6 gap-y-0">
          <CheckItem label="پرداخت پیش‌فرض"           checked={form.systemSettings.isDefaultPayment}      onChange={(v) => set("systemSettings.isDefaultPayment", v)} />
          <CheckItem label="نیاز به تأیید مدیر"       checked={form.systemSettings.requireManagerApproval} onChange={(v) => set("systemSettings.requireManagerApproval", v)} />
          <CheckItem label="ویرایش پس از ثبت مجاز"    checked={form.systemSettings.allowEditAfterPost}    onChange={(v) => set("systemSettings.allowEditAfterPost", v)} />
          <CheckItem label="تولید خودکار سند"         checked={form.systemSettings.autoGenerateDocument}  onChange={(v) => set("systemSettings.autoGenerateDocument", v)} />
        </div>
      </div>
    </div>
  );
}

// ─── پنل فرم سمت راست ─────────────────────────────────────────────────────────
function RightPanel({ form, set, isNew, saving, onSave, onCancel, error, codeRef }) {
  if (!form) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center py-20 text-muted-foreground">
        <Wallet className="h-14 w-14 mb-4 opacity-20" />
        <p className="text-sm font-medium">نوع پرداختی انتخاب نشده</p>
        <p className="text-xs mt-1">از لیست سمت چپ انتخاب کنید یا نوع جدید بسازید</p>
      </div>
    );
  }

  const SECTIONS = [
    { id: "s1", title: "اطلاعات اصلی",          icon: Info,     comp: <Section1 form={form} set={set} codeRef={codeRef} /> },
    { id: "s2", title: "تنظیمات حسابداری",      icon: Building2, comp: <Section2 form={form} set={set} /> },
    { id: "s3", title: "الزامات ثبت",            icon: FileCheck, comp: <Section3 form={form} set={set} /> },
    { id: "s4", title: "تنظیمات و محدودیت‌ها",  icon: Settings2, comp: <Section4 form={form} set={set} /> },
  ];

  return (
    <div className="flex flex-col h-full overflow-hidden">
      {/* عنوان فرم */}
      <div className="flex items-center justify-between px-5 py-3 border-b bg-muted/20 shrink-0">
        <div>
          <h2 className="font-bold text-sm">
            {isNew ? "تعریف نوع پرداخت جدید" : `ویرایش: ${form.title || form.code}`}
          </h2>
          {!isNew && form.code && (
            <p className="text-xs text-muted-foreground mt-0.5">{form.code}</p>
          )}
        </div>
        {!isNew && (
          <button onClick={onCancel} className="p-1.5 rounded-lg hover:bg-accent text-muted-foreground hover:text-foreground transition-colors">
            <X className="h-4 w-4" />
          </button>
        )}
      </div>

      {/* محتوا */}
      <div className="flex-1 overflow-y-auto px-5 py-4 space-y-6">
        {error && (
          <div className="text-xs text-destructive bg-destructive/10 rounded-lg px-3 py-2.5">{error}</div>
        )}
        {SECTIONS.map(({ id, comp }) => (
          <div key={id} className="space-y-2">{comp}</div>
        ))}
      </div>

      {/* فوتر */}
      <div className="border-t px-5 py-3 flex items-center justify-between shrink-0 bg-muted/10">
        <div className="flex items-center gap-2">
          <input
            type="checkbox"
            id="isActiveFoot"
            checked={form.isActive}
            onChange={(e) => set("isActive", e.target.checked)}
            className="h-4 w-4 rounded"
          />
          <Label htmlFor="isActiveFoot" className="text-sm cursor-pointer">فعال باشد</Label>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={onCancel} disabled={saving}>انصراف</Button>
          <Button size="sm" onClick={onSave} disabled={saving} className="min-w-[110px]">
            {saving && <RefreshCw className="h-3.5 w-3.5 animate-spin ml-1.5" />}
            {isNew ? "ایجاد نوع پرداخت" : "ذخیره تغییرات"}
          </Button>
        </div>
      </div>
    </div>
  );
}

// ─── دیالوگ تأیید حذف ─────────────────────────────────────────────────────────
function DeleteDialog({ item, onConfirm, onCancel }) {
  return (
    <AnimatePresence>
      {item && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm" dir="rtl">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className="bg-background rounded-2xl shadow-2xl w-full max-w-sm mx-4 p-6 border"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="h-10 w-10 rounded-full bg-destructive/10 flex items-center justify-center">
                <Trash2 className="h-5 w-5 text-destructive" />
              </div>
              <div>
                <h3 className="font-bold text-sm">حذف نوع پرداخت</h3>
                <p className="text-xs text-muted-foreground">این عملیات قابل بازگشت نیست</p>
              </div>
            </div>
            <p className="text-sm mb-5">
              آیا از حذف <span className="font-bold">{item.title}</span> (<span className="font-mono text-xs">{item.code}</span>) اطمینان دارید؟
            </p>
            <div className="flex gap-2 justify-end">
              <Button variant="outline" size="sm" onClick={onCancel}>انصراف</Button>
              <Button variant="destructive" size="sm" onClick={onConfirm}>بله، حذف شود</Button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}

// ─── آیتم لیست ────────────────────────────────────────────────────────────────
function ListItem({ item, isSelected, onSelect, onEdit, onToggle, onDelete }) {
  const methodColor = METHOD_COLORS[item.method] || "bg-gray-100 text-gray-700";
  return (
    <motion.div
      layout
      initial={{ opacity: 0, x: -10 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -10 }}
      onClick={() => onSelect(item)}
      className={`group relative flex items-center gap-3 px-3 py-2.5 rounded-xl border cursor-pointer transition-all
        ${isSelected
          ? "bg-primary/5 border-primary/30 shadow-sm"
          : "bg-background border-transparent hover:border-border hover:bg-muted/30"}
        ${!item.isActive ? "opacity-50" : ""}
      `}
    >
      {/* رنگ */}
      <div
        className="h-8 w-8 rounded-lg shrink-0 flex items-center justify-center text-white text-xs font-bold"
        style={{ backgroundColor: item.color || "#6366f1" }}
      >
        {item.code?.slice(0, 2)}
      </div>

      {/* اطلاعات اصلی */}
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-1.5 flex-wrap">
          <span className={`text-sm font-semibold ${!item.isActive ? "line-through text-muted-foreground" : ""}`}>
            {item.title}
          </span>
          {item.isDefault && (
            <Badge variant="secondary" className="text-[10px] px-1.5 py-0">پیش‌فرض</Badge>
          )}
        </div>
        <div className="flex items-center gap-1.5 mt-0.5">
          <span className="font-mono text-[10px] text-muted-foreground">{item.code}</span>
          <span className={`text-[10px] px-1.5 py-0.5 rounded-full font-medium ${methodColor}`}>
            {item.method}
          </span>
        </div>
      </div>

      {/* دکمه‌های عملیات */}
      <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity">
        <button
          onClick={(e) => { e.stopPropagation(); onEdit(item); }}
          className="p-1.5 rounded-lg hover:bg-accent text-muted-foreground hover:text-foreground"
          title="ویرایش"
        >
          <Pencil className="h-3.5 w-3.5" />
        </button>
        <button
          onClick={(e) => { e.stopPropagation(); onToggle(item); }}
          className="p-1.5 rounded-lg hover:bg-accent text-muted-foreground hover:text-foreground"
          title={item.isActive ? "غیرفعال کردن" : "فعال کردن"}
        >
          <Power className="h-3.5 w-3.5" />
        </button>
        <button
          onClick={(e) => { e.stopPropagation(); onDelete(item); }}
          className="p-1.5 rounded-lg hover:bg-destructive/10 text-muted-foreground hover:text-destructive"
          title="حذف"
        >
          <Trash2 className="h-3.5 w-3.5" />
        </button>
      </div>
    </motion.div>
  );
}

// ─── کامپوننت اصلی ────────────────────────────────────────────────────────────
export default function PaymentTypes() {
  const [types, setTypes]               = useState([]);
  const [loading, setLoading]           = useState(true);
  const [search, setSearch]             = useState("");
  const [filterMethod, setFilterMethod] = useState("");
  const [selectedId, setSelectedId]     = useState(null);
  const [isNew, setIsNew]               = useState(false);
  const [form, setForm]                 = useState(null);
  const [saving, setSaving]             = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState(null);
  const [toast, setToast]               = useState(null);
  const [seeding, setSeeding]           = useState(false);
  const [formError, setFormError]       = useState("");
  const codeRef = useRef(null);

  // ─── بارگذاری لیست ──────────────────────────────────────────────────────────
  const loadTypes = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (search)       params.set("search", search);
      if (filterMethod) params.set("method", filterMethod);
      const res = await api.get(`/api/payment-types?${params.toString()}`);
      setTypes(res.data?.data ?? []);
    } catch {
      setTypes([]);
    } finally {
      setLoading(false);
    }
  }, [search, filterMethod]);

  useEffect(() => { loadTypes(); }, [loadTypes]);

  // ─── setter عمیق برای nested path ───────────────────────────────────────────
  const set = useCallback((path, val) => {
    setForm((prev) => {
      const keys = path.split(".");
      if (keys.length === 1) return { ...prev, [path]: val };
      const top = keys[0];
      return { ...prev, [top]: { ...prev[top], [keys[1]]: val } };
    });
  }, []);

  // ─── انتخاب آیتم از لیست ────────────────────────────────────────────────────
  const handleSelect = (item) => {
    setSelectedId(item._id);
    setIsNew(false);
    setForm({ ...emptyForm(), ...item });
    setFormError("");
  };

  // ─── فرم جدید ───────────────────────────────────────────────────────────────
  const handleNew = () => {
    setSelectedId(null);
    setIsNew(true);
    setForm(emptyForm());
    setFormError("");
    setTimeout(() => codeRef.current?.focus(), 100);
  };

  // ─── لغو ────────────────────────────────────────────────────────────────────
  const handleCancel = () => {
    setSelectedId(null);
    setIsNew(false);
    setForm(null);
    setFormError("");
  };

  // ─── ذخیره ──────────────────────────────────────────────────────────────────
  const handleSave = async () => {
    if (!form.code?.trim() || !form.title?.trim()) {
      setFormError("کد و عنوان نوع پرداخت الزامی است");
      return;
    }
    setSaving(true);
    setFormError("");
    try {
      if (isNew) {
        await api.post("/api/payment-types", form);
        setToast({ msg: "نوع پرداخت با موفقیت ایجاد شد", type: "success" });
      } else {
        await api.put(`/api/payment-types/${selectedId}`, form);
        setToast({ msg: "تغییرات با موفقیت ذخیره شد", type: "success" });
      }
      handleCancel();
      await loadTypes();
    } catch (e) {
      setFormError(e?.response?.data?.message ?? e?.message ?? "خطا در ذخیره");
    } finally {
      setSaving(false);
    }
  };

  // ─── تغییر وضعیت ────────────────────────────────────────────────────────────
  const handleToggle = async (item) => {
    try {
      await api.patch(`/api/payment-types/${item._id}/toggle`);
      setToast({ msg: `وضعیت "${item.title}" تغییر کرد`, type: "success" });
      await loadTypes();
      if (selectedId === item._id) {
        const res = await api.get(`/api/payment-types/${item._id}`);
        setForm({ ...emptyForm(), ...res.data?.data });
      }
    } catch (e) {
      setToast({ msg: e?.response?.data?.message ?? "خطا", type: "error" });
    }
  };

  // ─── حذف ────────────────────────────────────────────────────────────────────
  const handleDelete = async () => {
    if (!deleteConfirm) return;
    try {
      const res = await api.delete(`/api/payment-types/${deleteConfirm._id}`);
      const msg = res.data?.message ?? "عملیات انجام شد";
      setToast({ msg, type: "success" });
      if (selectedId === deleteConfirm._id) handleCancel();
      await loadTypes();
    } catch (e) {
      setToast({ msg: e?.response?.data?.message ?? "خطا در حذف", type: "error" });
    } finally {
      setDeleteConfirm(null);
    }
  };

  // ─── بارگذاری پیش‌فرض‌ها ────────────────────────────────────────────────────
  const handleSeed = async () => {
    setSeeding(true);
    try {
      const res = await api.post("/api/payment-types/seed");
      setToast({ msg: res.data?.message ?? "پیش‌فرض‌ها بارگذاری شدند", type: "success" });
      await loadTypes();
    } catch (e) {
      setToast({ msg: e?.response?.data?.message ?? "خطا", type: "error" });
    } finally {
      setSeeding(false);
    }
  };

  const filteredTypes = types;

  return (
    <PageShell dir="rtl">
      <PageHeader
        title="تعریف انواع پرداخت"
        description="مدیریت و تعریف انواع روش‌های پرداخت مورد استفاده در سیستم"
      >
        <Button variant="outline" size="sm" onClick={handleSeed} disabled={seeding}>
          {seeding ? <RefreshCw className="h-3.5 w-3.5 animate-spin ml-1.5" /> : <Download className="h-3.5 w-3.5 ml-1.5" />}
          بارگذاری پیش‌فرض‌ها
        </Button>
        <Button size="sm" onClick={handleNew}>
          <Plus className="h-4 w-4 ml-1.5" />
          نوع پرداخت جدید
        </Button>
      </PageHeader>

      <div className="flex gap-4 h-[calc(100vh-10rem)]" dir="rtl">
        {/* ─── پنل چپ: لیست ─────────────────────────────────────────────────── */}
        <div className="w-[35%] min-w-[260px] flex flex-col gap-3">
          {/* جستجو */}
          <div className="relative">
            <Search className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="جستجو در کد یا عنوان..."
              className="h-9 pr-9"
            />
          </div>

          {/* فیلتر روش */}
          <div className="flex flex-wrap gap-1.5">
            <button
              onClick={() => setFilterMethod("")}
              className={`text-[11px] px-2.5 py-1 rounded-full border transition-colors
                ${!filterMethod ? "bg-primary text-primary-foreground border-primary" : "border-input text-muted-foreground hover:border-primary/50"}`}
            >
              همه
            </button>
            {METHODS.map((m) => (
              <button
                key={m}
                onClick={() => setFilterMethod(filterMethod === m ? "" : m)}
                className={`text-[11px] px-2.5 py-1 rounded-full border transition-colors
                  ${filterMethod === m ? "bg-primary text-primary-foreground border-primary" : "border-input text-muted-foreground hover:border-primary/50"}`}
              >
                {m}
              </button>
            ))}
          </div>

          {/* لیست */}
          <div className="flex-1 overflow-y-auto space-y-1 pr-1">
            {loading ? (
              <div className="space-y-2 pt-2">
                {[...Array(6)].map((_, i) => (
                  <div key={i} className="h-14 animate-pulse rounded-xl bg-muted" />
                ))}
              </div>
            ) : filteredTypes.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 text-muted-foreground text-center">
                <CreditCard className="h-10 w-10 mb-3 opacity-20" />
                <p className="text-sm">موردی یافت نشد</p>
              </div>
            ) : (
              <AnimatePresence>
                {filteredTypes.map((item) => (
                  <ListItem
                    key={item._id}
                    item={item}
                    isSelected={selectedId === item._id}
                    onSelect={handleSelect}
                    onEdit={handleSelect}
                    onToggle={handleToggle}
                    onDelete={setDeleteConfirm}
                  />
                ))}
              </AnimatePresence>
            )}
          </div>

          {/* شمارنده */}
          <p className="text-xs text-muted-foreground text-center">
            {filteredTypes.length} نوع پرداخت
          </p>
        </div>

        {/* ─── پنل راست: فرم ─────────────────────────────────────────────────── */}
        <div className="flex-1 rounded-xl border bg-background shadow-sm overflow-hidden">
          <RightPanel
            form={form}
            set={set}
            isNew={isNew}
            saving={saving}
            onSave={handleSave}
            onCancel={handleCancel}
            error={formError}
            codeRef={codeRef}
          />
        </div>
      </div>

      <DeleteDialog
        item={deleteConfirm}
        onConfirm={handleDelete}
        onCancel={() => setDeleteConfirm(null)}
      />

      <Toast toast={toast} onClose={() => setToast(null)} />
    </PageShell>
  );
}
